import { buildOpenScadArgs } from './args.js';
import { extensionForFormat, mimeTypeForFormat } from './formats.js';
import {
  type OpenScadExportInput,
  type OpenScadExportResult,
  type OpenScadRunResult,
  type OpenScadRunner,
  type OpenScadValidateInput
} from './OpenScadRunner.js';

const MOCK_STL = `solid mock
  facet normal 0 0 1
    outer loop
      vertex 0 0 0
      vertex 1 0 0
      vertex 0 1 0
    endloop
  endfacet
  facet normal 0 0 1
    outer loop
      vertex 1 0 0
      vertex 1 1 0
      vertex 0 1 0
    endloop
  endfacet
endsolid mock
`;

export class MockOpenScadRunner implements OpenScadRunner {
  async validate(input: OpenScadValidateInput): Promise<OpenScadRunResult> {
    const started = performance.now();
    const stderr = input.scad.includes('mock_error')
      ? 'ERROR: Mock parser error in file input.scad, line 1'
      : '';

    return {
      ok: stderr.length === 0,
      diagnostics: stderr
        ? [{ level: 'error', message: 'Mock parser error in file input.scad, line 1', line: 1 }]
        : [],
      stdout: 'Mock OpenSCAD validation completed.',
      stderr,
      elapsedMs: Math.round(performance.now() - started)
    };
  }

  async export(input: OpenScadExportInput): Promise<OpenScadExportResult> {
    const started = performance.now();
    const filename = `output${extensionForFormat(input.format)}`;
    const args = buildOpenScadArgs({
      inputPath: '/mock/input.scad',
      outputPath: `/mock/${filename}`,
      format: input.format,
      defines: input.defines,
      enableManifold: input.enableManifold
    });

    const data =
      input.format === 'stl'
        ? Buffer.from(MOCK_STL, 'utf8')
        : Buffer.from(`mock ${input.format} artifact generated by ${args.join(' ')}`, 'utf8');

    return {
      ok: true,
      diagnostics: [],
      stdout: `Mock OpenSCAD export completed as ${mimeTypeForFormat(input.format)}.`,
      stderr: '',
      elapsedMs: Math.round(performance.now() - started),
      format: input.format,
      filename,
      data,
      summary: input.summaryFile
        ? {
            geometry: {
              bounding_box: {
                min: [0, 0, 0],
                max: [1, 1, 0]
              },
              facets: 2,
              triangular: true
            }
          }
        : undefined
    };
  }
}
